curl -X POST http://localhost:3000/api/crud \
  -H "Content-Type: application/json" \
  -d '{ 
    "data": [
      {
        "group": "teste",
        "tickets": [
          {
            "id": 1,
            "conversations": [
              { "id": 123 }
            ]
          }
        ]
      }
    ]
  }'
